### ISSUE TITLE
black screen on ubuntu 18.04

### ISSUE THREAD

**Issue by rusins** [MarianArlt/sddm-chili#6]
System journal log:
```aug 26 04:10:55 kolba sddm-greeter[6889]: Loading file:///usr/share/sddm/themes/chili/Main.qml...
aug 26 04:10:55 kolba sddm-greeter[6889]: file:///usr/share/sddm/themes/chili/Main.qml:211:21: QML PropertyChanges: Cannot assign to non-existent property "y"
aug 26 04:10:56 kolba sddm-greeter[6889]: file:///usr/share/sddm/themes/chili/Main.qml:212: ReferenceError: mainStack is not defined
aug 26 04:10:56 kolba sddm-greeter[6889]: Adding view for "DVI-I-1" QRect(0,0 1600x1200)
aug 26 04:10:56 kolba sddm-greeter[6889]: Loading file:///usr/share/sddm/themes/chili/Main.qml...
aug 26 04:10:56 kolba sddm-greeter[6889]: file:///usr/share/sddm/themes/chili/Main.qml:211:21: QML PropertyChanges: Cannot assign to non-existent property "y"
aug 26 04:10:56 kolba sddm-greeter[6889]: file:///usr/share/sddm/themes/chili/Main.qml:212: ReferenceError: mainStack is not defined

**Comment by rusins** [comment]
I think I have the Ubuntu equivalent qt5 packages installed, but am not sure.

**Comment by MarianArlt** [comment]
Hmm,...this seems to be related to the virtual keyboard ~~which is weird because it may be upstream~~. The code is taken directly from the original breeze theme.
~~Would you mind try to install `qt5-virtualkeyboard`, see if that helps anything and get back in touch?~~

~~Sure hasn't happened to me before on any arch based system. SDDM has quite some issues actually.~~

**Comment by MarianArlt** [comment]
I just found that this is on my behalf. The virtualkeyboard part is shamelessly copy pasted and I didn't change the referred ID...Gonna fix this as soon as possible.

**Comment by rusins** [comment]
Hmm, running it with `sddm-greeter` works perfectly fine however :thinking:

**Comment by MarianArlt** [comment]
Yeah weird, that's definitely why I published it that way in the first place. 
Please update to v0.1.5 from within system settings and get back to me. Thank you for the feedback.

**Comment by rusins** [comment]
Well, I downloaded the latest master branch from here and tried again, but still the same issue persists. :/ I'm moving away unfortunately, so won't have an Ubuntu computer to test with no longer. Good luck!

**Comment by zougloub** [comment]
Can confirm the issue happens with the current code. Trying to find a non-KDE theme that support the virtual keyboard to compare...

**Comment by MarianArlt** [comment]
There's 259 open issues on the [SDDM page](https://github.com/sddm/sddm/issues) as of friday, october 12. Searching for open issues with the words "black screen" throws 27 open and 39 closed reports. This is bad...

**Comment by MarianArlt** [comment]
Closing due to inactivity. Feel free to comment again and I'll re-open.
